# Generated by Django 2.0.2 on 2018-04-08 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dndpal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='wisdowm',
            new_name='wisdom',
        ),
        migrations.RemoveField(
            model_name='feat',
            name='id',
        ),
        migrations.RemoveField(
            model_name='spells',
            name='component_1',
        ),
        migrations.RemoveField(
            model_name='spells',
            name='component_2',
        ),
        migrations.AddField(
            model_name='feat',
            name='name',
            field=models.CharField(default='', help_text='Enter the name of the feat', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='spells',
            name='components',
            field=models.CharField(default='', help_text='Enter the spell components to cast this spell', max_length=10000),
        ),
        migrations.AddField(
            model_name='subracefeatures',
            name='sub_feature_name',
            field=models.CharField(default='', help_text='Enter the name of this feature', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='featranking',
            name='name',
            field=models.CharField(default='', help_text='Enter the name of the feat this ranking describes', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='spells',
            name='area_effected',
            field=models.CharField(default='', help_text='Enter the area affected by the spell after it connects (in feet).', max_length=10000),
        ),
        migrations.AlterField(
            model_name='spells',
            name='range',
            field=models.CharField(default='', help_text='Enter the range of the spell in feet. If the range is infinite, enter the value: TBD', max_length=10000),
        ),
        migrations.AlterField(
            model_name='subracefeatures',
            name='name',
            field=models.CharField(default='', help_text='Enter the name of the subrace', max_length=100, primary_key=True),
        ),
    ]
