# Generated by Django 2.0.2 on 2018-04-08 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dndpal', '0003_auto_20180407_2020'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Spells',
            new_name='Spell',
        ),
        migrations.AlterField(
            model_name='subracefeatures',
            name='name',
            field=models.CharField(default='', help_text='Enter the name of the subrace', max_length=100, primary_key=True),
        ),
    ]
