# Generated by Django 2.0.2 on 2018-04-12 22:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dndpal', '0005_auto_20180410_1846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='name',
            new_name='cName',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='character_class',
            new_name='char_class',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='max_hit',
            new_name='max_hp',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='profeciencies',
            new_name='proficiency_list',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='temp_hit',
            new_name='temp_hp',
        ),
        migrations.RemoveField(
            model_name='character',
            name='id',
        ),
        migrations.RemoveField(
            model_name='character',
            name='initiative',
        ),
        migrations.RemoveField(
            model_name='character',
            name='speed',
        ),
        migrations.AddField(
            model_name='character',
            name='ability_list',
            field=models.CharField(default='', help_text='Enter the list of abilities for this character in JSON format.', max_length=1000),
        ),
        migrations.AddField(
            model_name='character',
            name='armor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dndpal.Armor'),
        ),
        migrations.AddField(
            model_name='character',
            name='bonus_list',
            field=models.CharField(default='', help_text='Enter the list of bonuses for this character in JSON format.', max_length=1000),
        ),
        migrations.AddField(
            model_name='character',
            name='char_id',
            field=models.PositiveIntegerField(default=1, help_text='Enter Character ID', primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='character',
            name='cur_hp',
            field=models.PositiveSmallIntegerField(default=1, help_text='Enter the current hitpoints for your character'),
        ),
        migrations.AddField(
            model_name='character',
            name='init',
            field=models.PositiveSmallIntegerField(default=1, help_text='Enter the initiative bonus for your character'),
        ),
        migrations.AddField(
            model_name='character',
            name='items',
            field=models.CharField(default='', help_text='Enter list of inventory items', max_length=5000),
        ),
        migrations.AddField(
            model_name='character',
            name='spell_list',
            field=models.CharField(default='', help_text='Enter the list of spells for this character in JSON format.', max_length=1000),
        ),
        migrations.AddField(
            model_name='character',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subracefeatures',
            name='name',
            field=models.CharField(default='', help_text='Enter the name of the subrace', max_length=100, primary_key=True),
        ),
    ]
