# Generated by Django 2.0.2 on 2018-04-12 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dndpal', '0007_auto_20180412_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='character_view',
            field=models.CharField(default='', help_text='Enter view for character (simple/guided/manual).', max_length=30),
        ),
        migrations.AlterField(
            model_name='subracefeatures',
            name='name',
            field=models.CharField(default='', help_text='Enter the name of the subrace', max_length=100, primary_key=True),
        ),
    ]
