# Generated by Django 2.0.4 on 2018-04-23 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dndpal', '0010_auto_20180422_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='description',
            field=models.CharField(default='', help_text='Enter the spell description', max_length=10000),
        ),
    ]
