# Generated by Django 2.0.4 on 2018-04-27 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dndpal', '0012_auto_20180424_0020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characterclass',
            name='skill_options',
        ),
        migrations.AddField(
            model_name='characterclass',
            name='skill_list',
            field=models.CharField(default='', help_text='Enter a comma separated spell list. Ex: "Acrobatics,Intimidation" \\(without the quotations\\)', max_length=100),
        ),
        migrations.AlterField(
            model_name='properties',
            name='description',
            field=models.CharField(default='', help_text='Enter the description of this property', max_length=10000),
        ),
    ]
