# Generated by Django 2.0.4 on 2018-04-28 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dndpal', '0014_auto_20180427_2251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='Enter the name of this property.', max_length=100)),
                ('description', models.CharField(default='', help_text='Enter the description of this property', max_length=10000)),
                ('weapon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dndpal.Weapon')),
            ],
        ),
    ]
