# Generated by Django 2.0.3 on 2018-03-29 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dndev', '0010_auto_20180328_0147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='characterclassfeatures',
            old_name='race',
            new_name='character_class',
        ),
        migrations.RemoveField(
            model_name='armor',
            name='armor_class',
        ),
        migrations.RemoveField(
            model_name='armor',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='character',
            name='character_money',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='price',
        ),
        migrations.RemoveField(
            model_name='subracefeatures',
            name='id',
        ),
        migrations.RemoveField(
            model_name='weapon',
            name='cost',
        ),
        migrations.AddField(
            model_name='armor',
            name='armor_bonus',
            field=models.SmallIntegerField(default=0, help_text='Enter the armor bonus for this item in pounds.'),
        ),
        migrations.AddField(
            model_name='armor',
            name='copper',
            field=models.IntegerField(default=0, help_text='Enter the copper-price component for this armor'),
        ),
        migrations.AddField(
            model_name='armor',
            name='gold',
            field=models.IntegerField(default=0, help_text='Enter the gold-price component for this armor'),
        ),
        migrations.AddField(
            model_name='armor',
            name='required_strength',
            field=models.SmallIntegerField(default=0, help_text='Enter the required strength to use this armor.'),
        ),
        migrations.AddField(
            model_name='armor',
            name='silver',
            field=models.IntegerField(default=0, help_text='Enter the silver-price component for this armor'),
        ),
        migrations.AddField(
            model_name='character',
            name='armor_class',
            field=models.PositiveSmallIntegerField(default=1, help_text='Enter the armor class for your character'),
        ),
        migrations.AddField(
            model_name='character',
            name='charisma',
            field=models.SmallIntegerField(default=0, help_text='Enter the charisma state for your character.'),
        ),
        migrations.AddField(
            model_name='character',
            name='constitution',
            field=models.SmallIntegerField(default=0, help_text='Enter the constitution state for your character.'),
        ),
        migrations.AddField(
            model_name='character',
            name='copper',
            field=models.IntegerField(default=0, help_text='Enter the gold of the character'),
        ),
        migrations.AddField(
            model_name='character',
            name='dexterity',
            field=models.SmallIntegerField(default=0, help_text='Enter the dexterity state for your character.'),
        ),
        migrations.AddField(
            model_name='character',
            name='gold',
            field=models.IntegerField(default=0, help_text='Enter the gold of the character'),
        ),
        migrations.AddField(
            model_name='character',
            name='initiative',
            field=models.PositiveSmallIntegerField(default=1, help_text='Enter the armor class for your character'),
        ),
        migrations.AddField(
            model_name='character',
            name='intelligence',
            field=models.SmallIntegerField(default=0, help_text='Enter the intelligence state for your character.'),
        ),
        migrations.AddField(
            model_name='character',
            name='max_hit',
            field=models.PositiveSmallIntegerField(default=1, help_text='Enter the max hitpoints for your character'),
        ),
        migrations.AddField(
            model_name='character',
            name='profeciencies',
            field=models.CharField(default='', help_text='Enter the list of proficiencies for this character in JSON format.', max_length=30),
        ),
        migrations.AddField(
            model_name='character',
            name='silver',
            field=models.IntegerField(default=0, help_text='Enter the gold of the character'),
        ),
        migrations.AddField(
            model_name='character',
            name='speed',
            field=models.PositiveSmallIntegerField(default=1, help_text='Enter the speed for your character'),
        ),
        migrations.AddField(
            model_name='character',
            name='strength',
            field=models.SmallIntegerField(default=0, help_text='Enter the strength state for your character.'),
        ),
        migrations.AddField(
            model_name='character',
            name='temp_hit',
            field=models.PositiveSmallIntegerField(default=1, help_text='Enter the temporary hitpoints for your character'),
        ),
        migrations.AddField(
            model_name='character',
            name='weapon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dndev.Weapon'),
        ),
        migrations.AddField(
            model_name='character',
            name='wisdowm',
            field=models.SmallIntegerField(default=0, help_text='Enter the wisdowm state for your character.'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='copper',
            field=models.IntegerField(default=0, help_text='Enter the copper-price component for this equipment'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='gold',
            field=models.IntegerField(default=0, help_text='Enter the gold-price component for this equipment'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='silver',
            field=models.IntegerField(default=0, help_text='Enter the silver-price component for this equipment'),
        ),
        migrations.AddField(
            model_name='subracefeatures',
            name='description',
            field=models.CharField(default='', help_text='Enter a description for these features', max_length=5000),
        ),
        migrations.AddField(
            model_name='subracefeatures',
            name='name',
            field=models.CharField(default='', help_text='Enter the name of this feature', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='weapon',
            name='copper',
            field=models.IntegerField(default=0, help_text='Enter the copper-price component for this weapon'),
        ),
        migrations.AddField(
            model_name='weapon',
            name='gold',
            field=models.IntegerField(default=0, help_text='Enter the gold-price component for this weapon'),
        ),
        migrations.AddField(
            model_name='weapon',
            name='silver',
            field=models.IntegerField(default=0, help_text='Enter the silver-price component for this weapon'),
        ),
        migrations.DeleteModel(
            name='Money',
        ),
    ]
