# Generated by Django 2.0.3 on 2018-03-27 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dndev', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('name', models.CharField(help_text='Enter the name of this class', max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Subrace',
            fields=[
                ('name', models.CharField(help_text='Enter the name of the subrace', max_length=100, primary_key=True, serialize=False)),
            ],
        ),
    ]
