# Generated by Django 2.0.3 on 2018-03-28 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dndev', '0005_character_alignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Money',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold', models.BigIntegerField(default=0, help_text='Enter the amount of gold for this character')),
                ('silver', models.BigIntegerField(default=0, help_text='Enter the amount of silver for this character')),
                ('copper', models.BigIntegerField(default=0, help_text='Enter the amount of copper for this character')),
            ],
        ),
        migrations.RemoveField(
            model_name='character',
            name='copper',
        ),
        migrations.RemoveField(
            model_name='character',
            name='gold',
        ),
        migrations.RemoveField(
            model_name='character',
            name='silver',
        ),
        migrations.AddField(
            model_name='race',
            name='speed',
            field=models.SmallIntegerField(default=0, help_text='Enter the speed for this race'),
        ),
    ]
