# Generated by Django 2.0.3 on 2018-03-28 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dndev', '0006_auto_20180327_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='character_money',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dndev.Money'),
        ),
    ]
