# Generated by Django 2.0.3 on 2018-03-28 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dndev', '0007_character_character_money'),
    ]

    operations = [
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('name', models.CharField(default='', help_text='Enter the name of the armor', max_length=100, primary_key=True, serialize=False)),
                ('armor_class', models.SmallIntegerField(default=0, help_text='Enter the weight for this item in pounds.')),
                ('max_dexterity', models.SmallIntegerField(default=0, help_text='Enter the weight for this item in pounds.')),
                ('is_stealth', models.BooleanField(default=False, help_text='Alan put something here :^)')),
                ('weight', models.SmallIntegerField(default=0, help_text='Enter the weight for this item in pounds.')),
                ('required_materials', models.CharField(default='', help_text='Enter the required materials to cast this spell in JSON format.', max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='CharacterClassFeatures',
            fields=[
                ('name', models.CharField(default='', help_text='Enter the name of this class feature', max_length=100, primary_key=True, serialize=False)),
                ('description', models.CharField(default='', help_text='Enter a description of this feature; i.e. what this feature does', max_length=5000)),
                ('required_level', models.SmallIntegerField(default=0, help_text='Enter the required level for this feature', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CharacterClassSpellList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_level', models.SmallIntegerField(default=0, help_text='Enter the required level for this spell', null=True)),
                ('ranking', models.SmallIntegerField(default=0, help_text='Enter the ranking of this spell relative to the other spells available for this class.', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CharacterClassStartingEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.SmallIntegerField(default=2, help_text='Enter the number of starting items this class starts with', null=True)),
                ('items', models.CharField(default='', help_text='Enter a list of the items in JSON format. Ex: {"item_1": "Spatula", "item_2": "Dishsoap"}', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='CharacterSubclass',
            fields=[
                ('name', models.CharField(default='', help_text='Enter the name of this Subclass', max_length=100, primary_key=True, serialize=False)),
                ('descrtiption', models.CharField(default='', help_text='Enter a description of this Subclass', max_length=1000)),
                ('required_level', models.SmallIntegerField(default=0, help_text='Enter the required level for this Subclass', null=True)),
                ('ranking', models.SmallIntegerField(default=0, help_text='Enter the ranking of this subclass relative to the other subclasses available for this class.', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CharacterSubclassSpellList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_level', models.SmallIntegerField(default=0, help_text='Enter the required level for this spell', null=True)),
                ('ranking', models.SmallIntegerField(default=0, help_text='Enter the ranking of this spell relative to the other spells available for this class.', null=True)),
                ('parent_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dndev.CharacterSubclass')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('name', models.CharField(default='', help_text='Enter the name of the equipment', max_length=100, primary_key=True, serialize=False)),
                ('weight', models.SmallIntegerField(default=0, help_text='Enter the weight for this item in pounds.')),
                ('descrtiption', models.CharField(default='', help_text='Enter a description of this item.', max_length=1000)),
                ('capacity', models.SmallIntegerField(default=0, help_text='Enter the amount of this item you have before any uses.')),
            ],
        ),
        migrations.CreateModel(
            name='Feat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrtiption', models.CharField(default='', help_text='Enter a description of this feat.', max_length=1000)),
                ('strength', models.SmallIntegerField(default=0, help_text='Enter the modification to the strength stat.')),
                ('dexterity', models.SmallIntegerField(default=0, help_text='Enter the modification to the dexterity stat.')),
                ('constitution', models.SmallIntegerField(default=0, help_text='Enter the modification to the constitution stat.')),
                ('intelligence', models.SmallIntegerField(default=0, help_text='Enter the modification to the intelligence stat.')),
                ('wisdowm', models.SmallIntegerField(default=0, help_text='Enter the modification to the wisdom stat.')),
                ('charisma', models.SmallIntegerField(default=0, help_text='Enter the modification to the charisma stat.')),
            ],
        ),
        migrations.CreateModel(
            name='FeatRankings',
            fields=[
                ('name', models.CharField(default='', help_text='Enter the name of the feat ranking', max_length=100, primary_key=True, serialize=False)),
                ('required_level', models.SmallIntegerField(default=0, help_text='Enter the required level for this spell', null=True)),
                ('ranking', models.SmallIntegerField(default=0, help_text='Enter the ranking of this feature relative to the other features available for this class.')),
            ],
        ),
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('name', models.CharField(default='', help_text='Enter the name of this property.', max_length=100, primary_key=True, serialize=False)),
                ('description', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dndev.CharacterSubclass')),
            ],
        ),
        migrations.CreateModel(
            name='RaceFeatures',
            fields=[
                ('name', models.CharField(default='', help_text='Enter the name of this race feature', max_length=100, primary_key=True, serialize=False)),
                ('description', models.CharField(default='', help_text='Enter a description of this feature; i.e. what this feature does', max_length=5000)),
                ('required_level', models.SmallIntegerField(default=0, help_text='Enter the required level for this feature', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Spells',
            fields=[
                ('name', models.CharField(default='', help_text='Enter the name of the spell', max_length=100, primary_key=True, serialize=False)),
                ('cast_time', models.PositiveIntegerField(default=6, help_text='Enter the amount of seconds it takes the spell to cast. If a spell takes 1 turn, enter in the value: TBD.')),
                ('damage', models.PositiveIntegerField(default=1, help_text='The base hit point damage of the spell. If this is a healing spell, enter in the amount of hit points it heals for')),
                ('range', models.PositiveIntegerField(default=10, help_text='Enter the range of the spell in feet. If the range is infinite, enter the value: TBD')),
                ('area_effected', models.PositiveIntegerField(default=1, help_text='Enter the area affected by the spell after it connects (in feet).')),
                ('required_materials', models.CharField(default='', help_text='Enter the required materials to cast this spell in JSON format.', max_length=10000)),
                ('component_1', models.CharField(default='', help_text='Enter the first component to cast this spell in JSON format.', max_length=10000)),
                ('component_2', models.CharField(default='', help_text='Enter the second component to cast this spell in JSON format.', max_length=10000)),
                ('school', models.CharField(choices=[('ab', 'Abjuration'), ('co', 'Conjuration'), ('di', 'Divination'), ('en', 'Enchantment'), ('ev', 'Evocation'), ('il', 'Illusion'), ('ne', 'Necromancy'), ('tr', 'Transmutation'), ('un', 'Universal')], default='ab', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='SubraceFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_level', models.SmallIntegerField(default=0, help_text='Enter the required level for this feature', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('name', models.CharField(default='', help_text='Enter the name of this weapon', max_length=100, primary_key=True, serialize=False)),
                ('damage', models.PositiveIntegerField(default=1, help_text='The base hit point damage of this weapon.')),
                ('damage_type', models.CharField(choices=[('ac', 'Acid'), ('bl', 'Bludgeoning'), ('co', 'Cold'), ('fi', 'Fire'), ('fo', 'Force'), ('li', 'Lightning'), ('ne', 'Necrotic'), ('pi', 'Piercing'), ('po', 'Poisoning'), ('ps', 'Psychic'), ('ra', 'Radiant'), ('sl', 'Slashing'), ('th', 'Thunder')], default='ab', max_length=2)),
                ('range', models.PositiveIntegerField(default=10, help_text='Enter the range of the weapon in feet.')),
                ('weight', models.SmallIntegerField(default=0, help_text='Enter the weight for this item in pounds.')),
            ],
        ),
        migrations.AddField(
            model_name='characterclass',
            name='skill_proficiency_limit',
            field=models.PositiveSmallIntegerField(default=5, help_text='Enter the max amount of skills this class can be proficient in'),
        ),
        migrations.AddField(
            model_name='race',
            name='description',
            field=models.CharField(default='', help_text='Enter a description of this race (backstory, beliefs, etc.)', max_length=5000),
        ),
        migrations.AddField(
            model_name='race',
            name='modifiers',
            field=models.CharField(default='', help_text='Enter the stats modifiers in JSON format. Ex: {"str": 2, "dex": 8}', max_length=20),
        ),
        migrations.AddField(
            model_name='subrace',
            name='description',
            field=models.CharField(default='', help_text='Enter a description of this sub-race (backstory, beliefs, etc.)', max_length=5000),
        ),
        migrations.AddField(
            model_name='subrace',
            name='parent_race',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dndev.Race'),
        ),
        migrations.AlterField(
            model_name='money',
            name='copper',
            field=models.BigIntegerField(default=0, help_text='Enter the amount of copper for this character or item'),
        ),
        migrations.AlterField(
            model_name='money',
            name='gold',
            field=models.BigIntegerField(default=0, help_text='Enter the amount of gold for this character or item'),
        ),
        migrations.AlterField(
            model_name='money',
            name='silver',
            field=models.BigIntegerField(default=0, help_text='Enter the amount of silver for this character or item'),
        ),
        migrations.AddField(
            model_name='weapon',
            name='cost',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dndev.Money'),
        ),
        migrations.AddField(
            model_name='subracefeatures',
            name='parent_subrace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dndev.Subrace'),
        ),
        migrations.AddField(
            model_name='racefeatures',
            name='race',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dndev.Race'),
        ),
        migrations.AddField(
            model_name='properties',
            name='weapon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dndev.Weapon'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='price',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dndev.Money'),
        ),
        migrations.AddField(
            model_name='charactersubclass',
            name='parent_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dndev.CharacterClass'),
        ),
        migrations.AddField(
            model_name='characterclassstartingequipment',
            name='character_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dndev.CharacterClass'),
        ),
        migrations.AddField(
            model_name='characterclassspelllist',
            name='character_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dndev.CharacterClass'),
        ),
        migrations.AddField(
            model_name='characterclassfeatures',
            name='race',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dndev.CharacterClass'),
        ),
        migrations.AddField(
            model_name='armor',
            name='cost',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dndev.Money'),
        ),
    ]
