# Generated by Django 2.0.3 on 2018-03-28 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dndev', '0008_auto_20180328_0131'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FeatRankings',
            new_name='FeatRanking',
        ),
    ]
