# Generated by Django 2.0.3 on 2018-03-28 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dndev', '0009_auto_20180328_0134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='charactersubclassspelllist',
            old_name='parent_class',
            new_name='subclass',
        ),
        migrations.RenameField(
            model_name='subracefeatures',
            old_name='parent_subrace',
            new_name='subrace',
        ),
    ]
