# Generated by Django 2.0.2 on 2018-04-07 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dndev', '0011_auto_20180329_0845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spells',
            name='component_2',
        ),
        migrations.AddField(
            model_name='subracefeatures',
            name='sub_feature_name',
            field=models.CharField(default='', help_text='Enter the name of this feature', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='spells',
            name='area_effected',
            field=models.CharField(default='', help_text='Enter the area affected by the spell after it connects (in feet).', max_length=10000),
        ),
        migrations.AlterField(
            model_name='spells',
            name='component_1',
            field=models.CharField(default='', help_text='Enter the spell components to cast this spell', max_length=10000),
        ),
        migrations.AlterField(
            model_name='subracefeatures',
            name='name',
            field=models.CharField(default='', help_text='Enter the name of the subrace', max_length=100, primary_key=True),
        ),
    ]
