# Generated by Django 2.0.2 on 2018-04-07 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dndev', '0012_auto_20180407_1943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spells',
            old_name='component_1',
            new_name='components',
        ),
        migrations.AlterField(
            model_name='spells',
            name='range',
            field=models.CharField(default='', help_text='Enter the range of the spell in feet. If the range is infinite, enter the value: TBD', max_length=10000),
        ),
        migrations.AlterField(
            model_name='subracefeatures',
            name='name',
            field=models.CharField(default='', help_text='Enter the name of the subrace', max_length=100, primary_key=True),
        ),
    ]
