# Generated by Django 2.0.2 on 2018-04-07 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dndev', '0013_auto_20180407_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feat',
            name='id',
        ),
        migrations.AddField(
            model_name='feat',
            name='name',
            field=models.CharField(default='', help_text='Enter the name of the feat', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='featranking',
            name='name',
            field=models.CharField(default='', help_text='Enter the name of the feat this ranking describes', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subracefeatures',
            name='name',
            field=models.CharField(default='', help_text='Enter the name of the subrace', max_length=100, primary_key=True),
        ),
    ]
