# Generated by Django 2.0.3 on 2018-03-27 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dndev', '0002_class_subrace'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Class',
            new_name='CharacterClass',
        ),
        migrations.AddField(
            model_name='character',
            name='character_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dndev.CharacterClass'),
        ),
        migrations.AddField(
            model_name='character',
            name='subrace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dndev.Subrace'),
        ),
    ]
